# Generated by Django 2.1.3 on 2018-12-31 07:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reading_statistics.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='无主题', max_length=60, verbose_name='主题')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博主')),
            ],
            options={
                'verbose_name': '博客',
                'ordering': ['-update'],
            },
            bases=(models.Model, reading_statistics.utils.GetReadInfo),
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60, verbose_name='博客类型')),
                ('blog', models.ManyToManyField(blank=True, to='blog.Blog')),
            ],
        ),
    ]
